# Generated by Django 4.1.3 on 2022-11-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_n', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('date_b', models.DateField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('time_b', models.TimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('table_b', models.CharField(max_length=2, verbose_name='Номер стола')),
                ('clients_n', models.CharField(max_length=2, verbose_name='Количество клиентов')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-date_b', '-time_b'],
            },
        ),
    ]
