# Generated by Django 4.1.3 on 2022-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='date_b',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='main',
            name='time_b',
            field=models.TimeField(verbose_name='Время бронирования'),
        ),
    ]
