# Generated by Django 4.1.3 on 2022-11-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category.html',
            new_name='category_id',
        ),
    ]
