# Generated by Django 4.1.3 on 2022-11-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date_p'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
